#
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Lint
        run: make lint

