#
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # Commit sha for v2.1.3
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Lint
        run: make lint

